#!/bin/bash
WD="$(dirname "$0")"
source $WD/config

which zx
which_res=$?

if [ $which_res -eq 0 ]
then
  echo "[INF] zx was found."
 else
  echo "[ERR] zx is not installed but is currently required for running SHX scripts. Please follow the instructions in https://www.npmjs.com/package/zx to install it."
  exit 1
fi

#export PATH="$PATH:$(pwd)/bin"
export SHX="0.1"

source $WD/aliases
