#!/bin/bash
WD="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

which zx >/dev/null 2>&1
which_res=$?

if [ $which_res -eq 0 ]
then
  echo "[INF] zx was found."
 else
  echo "[ERR] zx is not installed but is currently required for running SHX scripts. Please follow the instructions in https://www.npmjs.com/package/zx to install it."
  echo "[ERR] You can use the install-deps.sh script of SHX to install nvm if you do not have node installed."
  #exit 1
fi

if [[ "$PATH" == *"$WD/bin"* ]]
then
  echo "PATH already contains $WD/bin."
else
  export PATH="$PATH:$WD/bin"
fi

export SHX="0.1"
. $WD/aliases.sh
